### ISSUE TITLE
FOSDEM 2017 dinner

### ISSUE THREAD

**Issue by belenbarrospena** [opensourcedesign/events#54] opened 2016-12-07 07:57 UTC
The [notes from the December 6th meeting](https://github.com/opensourcedesign/events/issues/49#issuecomment-263360799) asked for an issue to organise our dinner on Friday before FOSDEM. So this is it. 

If you would like to come to dinner, please comment with your name and your dietary preferences, like so:

Belén Barros Pena (@belenbarrospena) - vegetarian

**Comment by ei8fdb** [comment] 2016-12-07 08:20
Bernard (@ei8fdb) - preferably meatatarian (or tasty vegatarian)

**Comment by evalica** [comment] 2016-12-07 10:20
Caty (@evalica) - any delicious food
Also I want to bring a +1. 
Regarding hour, after 20:00 would be great, since my flight lands at 18:20.

**Comment by eppfel** [comment] 2016-12-07 11:49
Felix – omnivorous 😉

**Comment by jancborchardt** [comment] 2016-12-07 14:12
Jan (@jancborchardt) – anything delicious too :D (lactose-free but I can choose that from the menu)

**Comment by gillisig** [comment] 2016-12-07 16:27
Gilli - Gluten, lactose and yeast free. Yes my stomach sucks! :)

**Comment by victoria-bondarchuk** [comment] 2016-12-12 07:43
Victoria (@victoria-bondarchuk) –  anything.  + @bzz –  anything

**Comment by elioqoshi** [comment] 2016-12-18 18:06
Probably me as well (coming with Mozilla, so hope we wont have overlapping plans). 
Elio - Omnivorous

**Comment by belenbarrospena** [comment] 2016-12-19 02:07
Would anybody object to inviting the submitters and speakers to come along? I can send a message to them, unless @evalica wants to do it to keep the contact person consistent :)

**Comment by ei8fdb** [comment] 2016-12-19 07:58
No objections here.

**Comment by evalica** [comment] 2016-12-19 11:01
I can do it, but I have no problem in Belen sending the invites. We are a community and everyone should help.

**Comment by belenbarrospena** [comment] 2016-12-19 12:28
Email sent. About the time, hopefully we can push it to 21:00 to give people enough time to arrive.

By the way, I don't know Brussels that well, so if anybody can recommend a place that has gluten, lactose and yeast free options, please comment!

**Comment by andreasn** [comment] 2016-12-19 13:00
I'm in!

**Comment by ghost** [comment] 2016-12-19 13:30
My Lê (@my-le) - any food
I can ask Bussels friends for new places to eat vegetarian, gluten and lactose free food. 
(Otherwise I know a nice lebanese restaurant that I advised last year to Mozilla Paris employees).

**Comment by belenbarrospena** [comment] 2016-12-19 13:33
Hi @my-le. Thanks for offering to help finding a place. Let me know what you find out :)

**Comment by karypun** [comment] 2016-12-19 15:05
@belenbarrospena Hello, would love to attend but need to confirm dates of my arrival with my organisation. What's the latest you'd need to know by?

**Comment by belenbarrospena** [comment] 2016-12-20 04:42
@karypun I wouldn't worry too much: I am sure we can make space if you turn up last minute :) Just let me know when you know.

**Comment by Incabell** [comment] 2016-12-20 14:37
I'd love to join too! 
Charlie (@incabell) - vegetarian

**Comment by qwazix** [comment] 2016-12-20 15:34
Me too, me too! (+1)

**Comment by PanderMusubi** [comment] 2016-12-20 17:13
Me too, no restrictions.

**Comment by 12people** [comment] 2016-12-21 11:29
I originally signed up here as interested, but now I've decided to come on Saturday morning instead, so I won't make it. Enjoy the dinner, though! :)

**Comment by belenbarrospena** [comment] 2016-12-29 05:16
Adding Raghu (no diet requirements), who emailed me about it

**Comment by 12people** [comment] 2016-12-29 17:55
Turns out I'll be attending after all, sorry for the mess. Allergic to soy, would prefer vegan, vegetarian is acceptable.

**Comment by ghost** [comment] 2016-12-30 08:54
I have created a pad with some restaurants suggestions.
Feel free to add yours: https://semestriel.framapad.org/p/Fosdem2017OpenDesign.

**Comment by belenbarrospena** [comment] 2017-01-06 07:45
Thanks @my-le for putting that list together. @jancborchardt, @gillisig and @12people: could you look at @my-le's list of restaurants, check the menus and see which one is better for your food needs? You can comment here with your preference. 

Please try and do so before Monday 10th. We really need to book soon since we are a big group!

**Comment by belenbarrospena** [comment] 2017-01-06 08:08
Me again :D 

I've created a Doodle list with the people who said are coming to dinner.

http://doodle.com/poll/4gqzwzs8z3vesqat

Since we all know things change ;) I am going to ask you to reconfirm in Doodle that you are coming. Please do that before Monday 9th. Otherwise I will assume you have changed your mind and won't be coming. Thanks!

**Comment by PanderMusubi** [comment] 2017-01-08 14:02
With that many people, not better to split the group in two?

**Comment by belenbarrospena** [comment] 2017-01-09 14:31
well, it looks like so far only 9 people have confirmed in Doodle, so that should be manageable by almost any restaurant

**Comment by belenbarrospena** [comment] 2017-01-09 14:44
About the restaurant, looking at @my-le's list Orientalia looks good to me

http://www.orientalia.be/accueil/

I will give people a couple of days to object and suggest something different. If nobody does, I will go ahead and book for 10 people.

**Comment by evalica** [comment] 2017-01-09 15:02
@belenbarrospena thanks Belen for your work. 

The problem I see with the restaurant is the location, being kind of far from the Grand-Place (especially if we plan to go after in Delirium).

**Comment by ghost** [comment] 2017-01-09 15:10
We can take the tram and walk to the Grand-Place, as I don't know much nice and vegetarian restaurants near to the Grand-Place, more touristic.
Otherwise, I can look for further restaurants.

In the list, this one is more close to the Grand-Place: 
Soul – Rue de la Samaritaine 20 (Sablon)
Bio fusion – Prices: 25€-30€ – www.soulresto.com

**Comment by ghost** [comment] 2017-01-09 15:30
@belenbarrospena @evalica there are veggie options in this Burger restaurant: 
Ellis Gourmet Burger – 4 Place Ste-Catherine 1000 Bruxelles 
http://ellisgourmetburger.be/fr/menu

**Comment by belenbarrospena** [comment] 2017-01-09 15:34
@evalica True. Orientalia is not that close to the centre, but there is always the tram as @my-le said. Soul also looks good though. Would that be better?

**Comment by belenbarrospena** [comment] 2017-01-09 15:36
I think I had dinner in Ellis a couple of years ago. It's good, but it seemed small. We would need to check if they can fit all 10 of us.

**Comment by belenbarrospena** [comment] 2017-01-09 15:38
ah, just checked. Ellis in St Catherine does not make reservations :(

**Comment by ghost** [comment] 2017-01-09 15:40
@belenbarrospena Ellis Gourmet: upstairs is nice for 8 people but 10, it's more difficult.
If we wish to eat there, some for us could be there when it opens (19:00?).

**Comment by belenbarrospena** [comment] 2017-01-09 16:47
there is also the place where we went last year. Does anybody remember the name?

**Comment by evalica** [comment] 2017-01-09 16:59
@belenbarrospena last year we went to http://www.kokob.be/menu-marquee/

**Comment by jancborchardt** [comment] 2017-01-10 22:25
@gillisig @victoria-bondarchuk @bzz @karypun @Incabell @qwazix you still need to confirm if you come or not at http://doodle.com/poll/4gqzwzs8z3vesqat#table :)

**Comment by qwazix** [comment] 2017-01-10 22:29
I inserted myself with my real name (Michael Demetriou) and then I saw that
there was already an entry with my username so I left a comment, as I
didn't see an obvious way to delete the entry.

**Comment by Incabell** [comment] 2017-01-10 22:47
Sorry, I had confirmed with Charlie, cause I didn't see my name there :/

**Comment by belenbarrospena** [comment] 2017-01-12 04:06
@qwazix, @incabell, no worries: I'll count you in. 

Thanks @evalica for the restaurant link. I will try and book there

**Comment by belenbarrospena** [comment] 2017-01-12 04:55
Right, I think we are 18, with 15 omnivores and 3 vegetarians. I suggest we order omnivore menu 1 for 15 and vegetarian menu 4 for 3. You can see the menus here
http://www.kokob.be/groups/

Looks like that should be 20 euro per head plus drinks.

I'll give it a day for you to object, then I'll email them to book :)

**Comment by PanderMusubi** [comment] 2017-01-12 09:23
Friend of mine who indicated here he would join forgot to fill out the Doodle, so a +1 for me please.

**Comment by Incabell** [comment] 2017-01-12 09:47
@belenbarrospena That sounds great! Thanks so much for organising this :D

**Comment by gillisig** [comment] 2017-01-12 10:16
Looks like I won't make it to FOSDEM this year unfortunately. So count me out. But have fun guys! :)

**Comment by karypun** [comment] 2017-01-13 13:25
@belenbarrospena thanks for organising. I'll be able to make it for dinner. No dietary restrictions from me and I've just updated Doodle with my response too! :)

**Comment by belenbarrospena** [comment] 2017-01-15 01:38
Thanks everybody. Looks like we are 20 now. Email sent to the restaurant: hopefully they can fit us.

**Comment by elioqoshi** [comment] 2017-01-15 13:12
When will the dinner be on Friday? My flight arrives 8pm so I might be a bit late

**Comment by belenbarrospena** [comment] 2017-01-16 02:26
@elioqoshi I've booked for 20:30. I could try moving it to 21:00, but from experience last year you would still  be late :( If you want to join us when you arrive, you are of course welcome, but I am not sure we'll be able to wait until you arrive for the food. Let me known what you want to do. 

If anybody else is in the same situation as @elioqoshi please let me know asap.

The booking is confirmed. I will send all details next week.

**Comment by belenbarrospena** [comment] 2017-01-20 17:47
Hi all, here comes the dinner info:

Where: 
[Kokob](http://www.kokob.be)
[Google maps](https://www.google.co.uk/maps/place/Kokob+Restaurant/@50.8455314,4.3465057,17z/data=!3m1!4b1!4m5!3m4!1s0x47c3c478552398ff:0xb57b465848358537!8m2!3d50.845528!4d4.3486944?hl=en)

When:
Friday, February 3rd at 20:30

Price: 
20 euro per person plus drinks. 

Please keep in mind that we will be charged for the 20 people we have booked for. This means that, if you don't turn up or cancel at the last minute, the rest of us will need to pay for you. So if you can no longer make it, let me know as soon as possible so that I can change the booking.

Looking forward to meeting you all in Brussels!

**Comment by evalica** [comment] 2017-01-21 08:04
Thank you @belenbarrospena for arranging this! See you soon.

**Comment by elioqoshi** [comment] 2017-01-21 09:31
Hmm this will be tight for me as I might need to check into my hotel first, so it's better if you cancel for me and I might join you later just for a drink (if that's still ok)

**Comment by karypun** [comment] 2017-01-23 09:47
Hi @belenbarrospena , I can't attend dinner now as I'm getting into Brussels later on Friday than anticipated.  If this is a problem, let me know. I'm terribly sorry.

**Comment by belenbarrospena** [comment] 2017-01-23 09:53
@elioqoshi @karypun no worries. Thanks for letting me know!

**Comment by evalica** [comment] 2017-01-24 14:57
@belenbarrospena I'm bringing another friend, so it was 2 (me+1), now we will be 3 (me+2). Thanks!

**Comment by belenbarrospena** [comment] 2017-01-25 09:36
@evalica thanks for letting me know! I will email the restaurant. I hope this is the last change: I'd say they hate my guts by now ;)

**Comment by ei8fdb** [comment] 2017-02-04 18:19
Can I have the honour of closing the "FOSDEM'17 dinner" issue?

It was lovely everyone! Thank you.

#62 opened in preparation for next years! :)

**Closed as completed by ei8fdb** 2017-02-04 18:19 UTC
