### ISSUE TITLE
FOSDEM 2018 - Booth

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/events#52] opened 2016-11-27 17:14 UTC
Are we going to have a booth at FOSDEM #64 ? I'd be happy to help, together with 2 colleagues of mine ( @rskikuli @giannisk ) from http://ura.design to talk about Open Source Design and ways to work

What do you think?

**Comment by belenbarrospena** [comment] 2016-11-28 03:01
The dealine to apply for a booth at FOSDEM is long past. Did anybody submit
an application for one?

**Comment by evalica** [comment] 2016-11-28 11:15
From this comment https://github.com/opensourcedesign/events/issues/41#issuecomment-241785070 I though @elioqoshi already submitted an application for a booth. I did not submit any booth application for OSD.

**Comment by belenbarrospena** [comment] 2016-11-28 11:41
@elioqoshi did write in that thread he would be submitting one for Ura, and that we could join forces. I am not sure what happened with that in the end. The list of accepted stands seems to be published now

https://fosdem.org/2017/stands/

**Comment by elioqoshi** [comment] 2016-11-28 12:31
Hmm, I seem to have forgotten that I needed to do that, my bad. Sorry about that :(
Impossible to ask now for a booth in a polite way?

**Comment by belenbarrospena** [comment] 2016-11-28 12:36
You could try, but I probably wouldn't. They are busy enough, and it's already very late. We can always try next year :)

**Comment by evalica** [comment] 2016-11-28 12:58
We can rename this issue for FOSDEM 2018 so we don't forget. Also a booth is better IMO when the sessions are on Saturday, so that people can come to the booth on Sunday to ask questions/help. So this year it wouldn't had been that convenient :) Let's do it next year!

**Comment by belenbarrospena** [comment] 2016-11-29 05:33
Sounds good :)

**Comment by evalica** [comment] 2017-09-04 09:14
According to the [Call for Participation 2017](https://www.fosdem.org/2018/news/2017-09-03-call-for-participation/) the deadline for Stands is 3 November. Who can handle the submission, organization, etc.?

**Comment by elioqoshi** [comment] 2017-09-08 15:47
I'd be happy to facilitate the submission for a booth if we have enough capacity to fill it.

Can we do it at OSD Summit?

**Comment by jancborchardt** [comment] 2017-09-10 14:25
Since we have limited time at the Summit, I’d say just like we do the devroom submission remotely we should also do the booth submission before. It’s really something we can do online and don’t have to spend the valuable 2–4 days in-person time for. :)

**Comment by belenbarrospena** [comment] 2017-09-15 06:54
@jancborchardt agreed. It's a simple form.

**Comment by elioqoshi** [comment] 2017-09-23 07:28
@belenbarrospena were you able to move forward with this?

**Comment by belenbarrospena** [comment] 2017-09-23 07:42
Not yet, no. Realised the deadline is not until November 3rd, so plenty of time still.

**Comment by elioqoshi** [comment] 2017-09-24 10:56
Ah okay, great then. Let me know if you need help.

**Comment by belenbarrospena** [comment] 2017-10-09 09:15
Hi all,

I've pasted below the application for our stand at FOSDEM. Deadline for submission is November 3rd, so plenty of time for everybody to read through and suggest changes. 

I would need a couple of things to complete the application: 

1. A link to the logo svg file. I think it used to be at [https://cloud.jancborchardt.net/s/opensourcedesignlogo](https://cloud.jancborchardt.net/s/opensourcedesignlogo) but it is no longer there. For the time being I've put the png file at [https://cloud.githubusercontent.com/assets/925062/23703062/57c3338a-03fe-11e7-9a52-8e14dc908e73.png](https://cloud.githubusercontent.com/assets/925062/23703062/57c3338a-03fe-11e7-9a52-8e14dc908e73.png)

2. @elioqoshi I would need an email address to put you as one of the contact people. 

# Stand proposal form

**Name of project:** 
Open Source Design

**Description of project(s) for publication:**
Open Source Design is a community of designers and developers advocating more open, human-centric and participatory design processes within free and open source software. We understand "design" in a broad sense, and our community includes interaction designers, content experts, design researchers, information architects, graphic designers, user experience professionals, and of course software developers. What we all share is the conviction that engaging users in the process of developing software results in better software.  

Our booth will be running a "design clinic", an informal one-to-one set up where you can sit down with a designer to talk about your FOSS project, ask questions and seek advice on diverse aspects of design, from usability testing to typography. Our volunteer designers have a mix of skills and experience, both in commercial settings and FOSS projects.

**Why does it fit FOSDEM?**
Open Source Design has been present at FOSDEM since 2015, when we organised our first devroom. Our sole purpose is advocating human-centric design within FOSS. Our devrooms have been well attended, and we have seen strong demand for design contributions. We believe running a design clinic this year can give us the opportunity to engage more actively with projects, and create opportunities for stable and long-term collaborations between designers and FOSS projects.

**Number of tables:**
One

**Primary contact:**
Belén Barros Pena

**Submitter's affinity to the project(s):**
I have been involved with Open Source Design since its inception. I was the main co-ordinator of the first and second devrooms in 2015 and 2016, and have been involved in the organisation of the subsequent devrooms in 2017 and 2018. 

**Secondary contact:**
Elio Qoshi

**Project website URL:**
http://opensourcedesign.net/

**Project logo URL:**
https://cloud.githubusercontent.com/assets/925062/23703062/57c3338a-03fe-11e7-9a52-8e14dc908e73.png

**Public contact email address:**
N/A

**Source code location:**
https://github.com/opensourcedesign

**Additional links (e.g. IRC, Google+, RSS, Twitter, Facebook, YouTube, mailing list etc.):**
Twitter: https://twitter.com/opensrcdesign
IRC: https://webchat.freenode.net/?channels=opensourcedesign
Forum: https://discourse.opensourcedesign.net/

**Special requirements:**
We would need a few extra chairs. The design clinic format requires visitors to sit down with the designer to have a quiet, and relatively long (15 to 30 mins) chat, often with a laptop in front of them. So having a few chairs where visitors can sit would be handy. We expect having between 2 and 4 designers available in the clinic at any given time, which means we would need 8 chairs overall.

**Comment by evalica** [comment] 2017-10-09 09:34
We have the logos on the website repo. You can use https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/images/opensourcedesign-logo.png

**Comment by belenbarrospena** [comment] 2017-10-09 09:35
Silly me: I should have checked there. 

Thanks @evalica !

**Comment by evalica** [comment] 2017-10-09 09:35
Number of chairs sounds a bit too much, considering they usually give like 1-2 per stand. If we have 2 more chairs, for a total of at least 4, I think it would be great.

**Comment by belenbarrospena** [comment] 2017-10-09 09:39
@evalica Agreed. I am not even sure we will fit 4 designers in a single table. But thought better not to be shy when asking, and see what we get ;)

**Comment by evalica** [comment] 2017-10-09 09:41
Belen, it looks great. Thanks for taking care of it. Hoping we will get a table. 

Another mention we could have is to have the booth in a different day than the devroom, although I think the booth is for both days. We could mention that we are interested in having the booth just one day, but maybe we want for both :)

**Comment by belenbarrospena** [comment] 2017-10-09 09:46
@evalica yes, that is one of the main things we need to decide. Do we have capacity to run the clinic for both days? Or should we do only Saturday?

To be honest, I am not sure what the impact of doing just one day could be in our chances to get a stand. I think they are expected to be up for the 2 days. As far as I know, having a stand for just one day is unusual, but I could be wrong. Maybe @jancborchardt and other people involved in other stands know more about this.

It would be good to hear what other people think about this issue of one vs. two days. Thanks for bringing it up @evalica !

**Comment by pdurbin** [comment] 2017-10-09 12:02
Looks great @belenbarrospena . Thanks!

**Comment by jancborchardt** [comment] 2017-10-09 20:56
I would also think all stands are for both days. I’m not aware of any details, but I haven’t really seen an stand be only there for one day, and I assume it’s not possible.

The proposal looks good, and I guess we’re enough people to be able to both maintain the room and the booth. :) If everyone just helps out a little here and there for a few hours it’s all good.

**Comment by belenbarrospena** [comment] 2017-10-10 08:50
Maybe we should count how many of us we'll be. Could you +1 this post if you know you are coming to FOSDEM for sure?

Thanks!

**Comment by belenbarrospena** [comment] 2017-10-11 16:04
Excellent, so it looks like we have 6 people for sure attending FOSDEM: 

@belenbarrospena
@evalica 
@elioqoshi 
@jancborchardt 
@andreasn 
@ei8fdb 

I am assuming there is a good chance @victoria-bondarchuk will also be there. 

This means we could have 3-4 people in the devroom on Sunday, and still have 2-3 people in the stand. @evalica : what do you think? Enough to manage two days for the stand? Since this is our first try and it is a bit of an experiment, I want to make sure everybody is confident we can handle it :)

**Comment by jancborchardt** [comment] 2017-10-11 23:33
@Incabell @jdittrich @bnvk @simonv3 @yoroy @dimitrieh @xuv @Xaviju @karmatosed will you also be at FOSDEM? :) And which other open source designers do you know who will be there who could help out and join our design devroom and booth? :)

**Comment by evalica** [comment] 2017-10-12 08:52
@belenbarrospena we'll manage somehow :) depends also on the location of the booth :) the only rule is not to leave the booth empty :)

**Comment by belenbarrospena** [comment] 2017-10-12 09:00
right: sounds we have reached some kind of agreement. I will submit it today.

**Comment by belenbarrospena** [comment] 2017-10-12 10:48
submitted!

**Comment by Incabell** [comment] 2017-10-12 10:57
@jancborchardt I will probably be there but since I can't guarantee it 100% I didn't want add myself to the list in the earlier comment.

**Comment by belenbarrospena** [comment] 2017-12-06 10:15
Our stand has been accepted for FOSDEM'18. We will be in level 1 of the K building. Congratulations to us all!! :)

The point of the stand is to run a design clinic, which means we'll need 2 to 3 people in the stand at any given time. Looking at the posts above, these are the people attending FOSDEM so far (in no particular order):

@evalica 
@elioqoshi 
@jancborchardt 
@andreasn 
@ei8fdb 
@victoria-bondarchuk 
@belenbarrospena

I have @Incabell as a "maybe". 

If anybody else is coming, and wants to provide design advice to projects in the stand, please let me know.

In order to organise the stand shifts, could you start by letting me know your availability? I would need to know when you are **not** available to be in the stand.

Thanks!!

**Comment by HeikoTietze** [comment] 2017-12-06 10:38
Will be around as well but likely have no time for the OSD booth. Nevertheless looking forward some talks.

**Comment by evalica** [comment] 2017-12-06 10:38
Hi Belen! This is great news! Do we have the stand for both days? 
I think it's a bit early to tell the availability, since the schedules are not in. I need also to be at the XWiki table. I estimate I can stay between 2-4 hours at our table.

**Comment by belenbarrospena** [comment] 2017-12-06 10:48
@evalica yes, stand is for both days. 2-4 hours sounds good. Thanks!

**Comment by tessgadwa** [comment] 2017-12-06 18:58
Hi, I should be available to be at the stand for at least some of the time.

**Comment by belenbarrospena** [comment] 2017-12-07 12:04
@tessgadwa Great. Thanks! :) I'll add you to the list

**Comment by elioqoshi** [comment] 2017-12-08 10:46
The whole Ura team will be at FOSDEM and each of us will be able to stay for at a few hours ideally (but we need to check whether we are needed somewhere else too).

cc @AnXh3L0 @borisbudini @silvaarapi @rskikuli

**Comment by belenbarrospena** [comment] 2017-12-11 09:16
Excellent! Thanks @elioqoshi 

I will add the Ura crowd to the list.

**Comment by jancborchardt** [comment] 2017-12-11 16:16
@belenbarrospena currently on the booths page it is linked to our Github:https://fosdem.org/2018/stands/ could we have that changed to http://opensourcedesign.net/ ? :)

**Comment by belenbarrospena** [comment] 2017-12-13 10:43
@jancborchardt I'll ask :)

**Comment by belenbarrospena** [comment] 2017-12-13 10:49
And one question for those who attended the Summit in Berlin: any swag left? Posters, stickers, etc?

Could we give them away in the stand? Can we order more for FOSDEM?

**Comment by evalica** [comment] 2017-12-13 10:55
@belenbarrospena We talked about this last night, at the meeting. There is some swag left, but @jancborchardt will order more, in order to have everything for FOSDEM. He mentioned (from what I remember) 1000 stickers, ? "looking for design..." cards, 2-3 posters.

**Comment by belenbarrospena** [comment] 2017-12-13 11:04
Wondrous! You people are always on top of things :)

Sorry I missed the meeting yesterday: completely forgot about it :/

**Comment by belenbarrospena** [comment] 2018-01-09 15:47
Hi all,

I won't manage the call today (Tuesday evenings are not a very good day for me), but I wanted to write a few things about the stand. 

Setup is from Saturday at 09:00 and we should be done by 16:00 to 16:30 on Sunday. Me and @ei8fdb will be setting up and wrapping up, although you are all of course welcome to help. Our stand is on the Level 1 of the K building (part of stands group C). 

The format is a design clinic: 2 or more designers will be there to answer questions about design. The idea is that projects can come with a demo, sit down with us, and discuss their design problems. We give them some high level advice as best we can :)

I am hoping we will also have some stickers and posters, which I believe @jancborchardt is taking care of. 

I have a list of 12 people who have confirmed they want to be at the stand: @evalica @elioqoshi @jancborchardt @andreasn @ei8fdb @victoria-bondarchuk @tessgadwa @AnXh3L0 @Borisbudini @silvaarapi and @rskikuli (+ me)

I have added you all to this Doodle poll, which has 2-hour shifts. 

https://doodle.com/poll/y7zb5e62e8xr9vqp

Feel free to change your shift(s) as needed, keeping in mind that we need at least 2 people per shift, and that it is important we all contribute to cover Sunday (even though we all also want to be at the devroom!). @victoria-bondarchuk and @evalica as the organisers of the devroom can skip Sunday at the stand :)

Any questions, issues, suggestions, etc, comment here!

**Comment by evalica** [comment] 2018-01-09 16:04
Hi @belenbarrospena the times are not quite right so maybe you can fix that for the Doodle pool (SAT starts at 12 PM until 08 PM; Sun from 12 PM to 6 PM - check what time zone has been set and maybe put it for Brussels). Thanks for creating the Doodle.

**Comment by evalica** [comment] 2018-01-09 16:28
Actually it can be manually changed from top, just be careful when agreeing on the time frame :)

**Comment by belenbarrospena** [comment] 2018-01-09 16:34
Mmm, weird. Times look right for me :/  Time zone selected is GMT (London).

I will try and change it when I get to a computer.

**Comment by jancborchardt** [comment] 2018-01-09 16:37
And regarding the design clinic part it’s also important to not get overloaded by people there. :) If more help is necessary, asking them to open a job on our [Open Source Design job board](http://opensourcedesign.net/jobs/) is best. Because there will be loads of people at FOSDEM, and generally people don’t hang out suuperlong at the stands.

**Comment by belenbarrospena** [comment] 2018-01-10 09:18
@evalica Doodle seems to block changes to the time zone once there are answers in the poll, so I can't change the time zone to GMT+1 :(

For clarity, these are the stand shifts:

Saturday 3rd Feb 10:00 - 12:00
Saturday 3rd Feb 12:00 - 14:00
Saturday 3rd Feb 14:00 - 16:00
Saturday 3rd Feb 16:00 - 18:00
Sunday 4th Feb 10:00 - 12:00
Sunday 4th Feb 12:00 - 14:00
Sunday 4th Feb 14:00 - 16:00

I hope this helps.

**Comment by jancborchardt** [comment] 2018-01-10 15:42
@belenbarrospena ok, in that case I can not take the slot of

> Sunday 4th Feb 12:00 - 14:00

that I’m assigned to as I have my talk then. ;)

The slot after it would be good, 14:00 – 16:00 works. (Same as on Saturday)

**Comment by elioqoshi** [comment] 2018-01-10 15:44
@marianaballa will be instead of @silvaarapi eventually (we need to check her time commitment as she is with the Fedora project as well).

@AnXh3L0 will be able to help out 1-2 hours every day as well.

We need a bit more time to check out shifts as well.

**Comment by belenbarrospena** [comment] 2018-01-10 16:26
@jancborchardt Just moved you to Sunday 14:00 to 16:00. Thanks!

@elioqoshi I've removed @silvaarapi and added @marianaballa. All three of you feel free to access the Doodle poll at any time and change your shifts as needed! :)

It's here: https://doodle.com/poll/y7zb5e62e8xr9vqp

**Comment by tessgadwa** [comment] 2018-01-14 19:55
I can take the slot of Saturday, February 3 14:00 - 16:00 PM. If other
people have signed up for this already, let me know. My schedule is pretty
flexible!

**Comment by belenbarrospena** [comment] 2018-01-17 07:36
Thanks @tessgadwa 

I've changed the Doodle poll to put you in that slot.

**Comment by elioqoshi** [comment] 2018-01-17 16:32
@rskikuli has his talk at 2:30pm on Sunday so that collides with his slot currently.

Coordinating with the Ura team and getting back here with more final slots.

**Comment by belenbarrospena** [comment] 2018-01-18 10:34
Sounds good. Thanks @elioqoshi

**Comment by belenbarrospena** [comment] 2018-01-28 08:40
Hi all, 

Posting here the organisers instructions so that everybody knows how the stands run.

If someone has an extension cable with European 2-pin plugs, please bring it with you. @ei8fdb and I will be bringing a 3-pin UK one.

Location
--------
Stands will be located in three buildings on the ULB campus: AW, H
and K. You can find the location of your stand on the FOSDEM site:
[https://fosdem.org/2018/stands/](https://fosdem.org/2018/stands/)

Timing
-------
Build-up starts from 9:00 on Saturday. Visitors will start arriving
around 10:00, and you can expect it to be properly busy by noon.
The Saturday program ends at 19:00; you're expected to be out of
the building at that time.

It is possible to start on your stand on Friday afternoon. However,
there is no exact time when the tables will be ready - so if you
arrive early, you will have be asked to help us set up those tables.

For the night between Saturday and Sunday, there are overnight storage
rooms in the H and K buildings. You can also leave stuff at your stand
overnight; the buildings will be closed overnight, but we cannot guard
the hallways on Sunday morning. We also cannot provide any insurance or
take responsibility in case of damage or theft. We do have security
staff on campus at all times.

Sunday starts around 9:00-10:00 and the teardown starts at 17:00. All
stand holders are expected to help clean up the area around their stand,
and the tables and table cloths should be returned to the collection
point by the stand holders. Your stand area should be cleared and
cleaned up and the tables returned to the collection point by 17:30.

Various
-------
The tables provided are 180x80cm wide. We also provide table cloths,
but you are more than welcome to provide any on your own, especially
if you have something like a banner for your project. There will be
two chairs provided per table. You may not tape posters to the walls
or windows near the stands.

We will provide you with a power socket. If you require more than
one, please bring extension cables. Note that Belgium uses type E
sockets: http://www.worldstandards.eu/electricity/plugs-and-sockets/
If you need any adapters, make sure to bring them along.

High-speed Internet uplink will be provided by means of WiFi everywhere.
If you have a device that requires a wired ethernet connection, bring a
bridge device with you.

Keep in mind that our Code of Conduct applies to stand organisers
as well. Read it at [https://fosdem.org/2018/practical/conduct/](https://fosdem.org/2018/practical/conduct/)

Stickers
--------------
It's probably worth mentioning again that stickers have been a
particular headache for FOSDEM in the past.

Please do your best to stop people putting them on the windows, walls,
furniture, the floor, toilet doors etc. as they will all have to be
carefully removed by us when we discover them and FOSDEM has to pay for
redecoration if there is any damage.

Similarly, please don't attach anything at all to walls or the
ceiling(!) etc.  If your stand has windows behind it and you have the
right quality of masking tape that leaves no mark after removal (maybe
test it on your own windows at home for a couple of days!), staff
(wearing yellow) might say it's OK to put up posters.

**Comment by belenbarrospena** [comment] 2018-01-31 12:06
Hi all, 

Just a quick reminder of your stand shifts

![stand_shifts](https://user-images.githubusercontent.com/684113/35622279-21481a08-067f-11e8-9f73-d1aec2b3ada6.png)

Any questions, let me know. See you in Brussels! :)

**Comment by tessgadwa** [comment] 2018-01-31 14:36
Thanks, Belen!

**Comment by evalica** [comment] 2018-02-07 14:20
Thanks everyone for your involvement! It was a great event!

**Closed as completed by evalica** 2018-02-07 14:20 UTC

**Comment by xuv** [comment] 2018-02-07 19:37
@evalica Great talk. I really enjoyed it. I could not be present in Brussels. But watched is on Peertube: https://video.tedomum.net/videos/watch/970957fc-c742-4139-a458-be0dfe43bd32

**Comment by evalica** [comment] 2018-02-08 08:33
Thanks @xuv :)
